

#ifneq (,$(filter $(CONFIG_GOODIX_SENSOR_TYPE), "GF3118M" ))
#  obj-y += GF3118M/
#endif

#ifneq (,$(filter $(CONFIG_GOODIX_SENSOR_TYPE), "GF3208" ))
#  obj-y += GF3208/
#endif

obj-$(CONFIG_GOODIX_FINGERPRINT) += $(CONFIG_GOODIX_SENSOR_TYPE)/
