# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y +=  gt1xx_tpd.o
obj-y	+=  gt1xx_generic.o
obj-y	+=  gt1xx_extents.o
obj-y	+=  gt1xx_update.o
obj-y +=  gt1xx_tools.o

