# Linux driver folder
ccflags-y += -I$(srctree)/drivers/spi/mediatek/$(MTK_PLATFORM)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/


obj-y += fpsensor_capture.o
obj-y += fpsensor_common.o
obj-y += fpsensor_input.o
obj-y += fpsensor_main.o
obj-y += fpsensor_platform.o